site_name: NeXtep's Blog
site_url: https://InTheFuture7.github.io/
site_author: NeXtep
theme:
    name: material #主题

    language: en
    palette:
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/link
            name: 关闭自动模式
        - media: "(prefers-color-scheme: light)"
          scheme: default # 日间模式
          rimary: blue grey # 上方的
          accent: blue # 链接等可交互元件的高亮色
          toggle:
            icon: material/toggle-switch # 图标
            name: 切换至夜间模式 # 鼠标悬浮提示
        - media: "(prefers-color-scheme: dark)"
          scheme: slate # 夜间模式
          primary: black 
          accent: indigo
          toggle:
            icon: material/toggle-switch-off-outline
            name: 切换至日间模式
    features:
        - navigation.tabs  # 顶部导航栏
        - navigation.sections
        - navigation.top        
        # - toc.integrate  # 目录
        - search.suggest
        - search.highlight  # 搜索高亮
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
        - navigation.top # 返回顶部的按钮 在上滑时出现


plugins:
    - search
    - blog

extra:
    social:
        - icon: fontawesome/brands/github-alt
          link: https://github.com/InTheFuture7

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
          generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list


nav:
    - 首页: index.md
    - 博客: 
        - blog/index.md
        - 机器学的数学基础: 
            - blog/math4ml/index.md
            - 1. 线性代数: blog/math4ml/linear_algebra.md
            - 2. 概率论: blog/math4ml/probability_theory.md
            - 3. 统计学: blog/math4ml/statistics.md    
    - 代码: code/index.md
    - 标签: tag/index.md
    - 工具: tool/index.md
    - 关于: about/index.md


copyright: |
    &copy; 2025 <a href="https://github.com/InTheFuture7"  target="_blank" rel="noopener">NeXtep</a>
