site_name: NeXtep's Blog
site_url: https://InTheFuture7.github.io/
site_author: NeXtep
theme:
    name: material #主题
    features:
        - navigation.tabs  # 顶部导航栏
        - navigation.sections
        - navigation.top        
        # - toc.integrate  # 目录
        - search.suggest
        - search.highlight  # 搜索高亮
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
    language: en

plugins:
    - search

extra:
    social:
        - icon: fontawesome/brands/github-alt
          link: https://github.com/InTheFuture7

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
          generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list

copyright: |
    &copy; 2025 <a href="https://github.com/InTheFuture7"  target="_blank" rel="noopener">NeXtep</a>
